<a href="https://colab.research.google.com/github/Avhi-kr/ds-practice/blob/main/OneHotEncoder_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [104]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [105]:
df=pd.read_csv("/content/carprices (1).csv")

In [106]:
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [107]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [108]:
a=df[['Car Model']]

In [109]:
b=ohe.fit_transform(a)

In [110]:
b = pd.DataFrame(
    b.toarray(),
    columns=ohe.get_feature_names_out(['Car Model'])  # ✅ all strings
)

In [111]:
df=df.drop(['Car Model'],axis='columns')

In [112]:
df=pd.concat([df,b], axis='columns')

In [113]:
df

    Mileage  Sell Price($)  ...  Car Model_BMW X5  Car Model_Mercedez Benz C class
0     69000          18000  ...               1.0                              0.0
1     35000          34000  ...               1.0                              0.0
2     57000          26100  ...               1.0                              0.0
3     22500          40000  ...               1.0                              0.0
4     46000          31500  ...               1.0                              0.0
5     59000          29400  ...               0.0                              0.0
6     52000          32000  ...               0.0                              0.0
7     72000          19300  ...               0.0                              0.0
8     91000          12000  ...               0.0                              0.0
9     67000          22000  ...               0.0                              1.0
10    83000          20000  ...               0.0                              1.0
11    79000          21000  ...               0.0                              1.0
12    59000          33000  ...               0.0                              1.0

[13 rows x 6 columns]

In [114]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [115]:
x=df.drop(['Sell Price($)'],axis='columns')
y=df['Sell Price($)']

In [116]:
model.fit(x,y)

LinearRegression()